### ISSUE TITLE
All Files gone all of sudden

### ISSUE THREAD

**Issue by MagniDK** [DisboxApp/web#113] opened 2024-05-05 12:58 UTC
![Screenshot 2024-05-05 145754](https://github.com/DisboxApp/web/assets/66169685/3c7de21e-efd7-4c45-bace-ec850f011ea1)

**Comment by DisboxApp** [comment] 2024-05-06 21:04
Hey, is this still happening?

**Comment by DisboxApp** [comment] 2024-05-06 21:05
Closing as duplicate of #112.

**Closed as completed by DisboxApp** 2024-05-06 21:05 UTC
