### ISSUE TITLE
upload multiple files

### ISSUE THREAD

**Issue by xnicknamex** [DisboxApp/web#56] opened 2023-09-12 17:49 UTC
how can i upload multiple files? i know that i cant upload a folder but is it possible to upload multiple files from one folder?

**Comment by DisboxApp** [comment] 2023-10-27 09:54
Hi, please provide more details on the issue or your discord username so I can message you privately and try to debug the issue with you. :)

**Comment by SploeCyber** [comment] 2024-01-03 09:52
++ This is a great idea

**Comment by DisboxApp** [comment] 2024-02-19 21:24
Duplicate of #8

**Closed by DisboxApp** 2024-02-19 21:24 UTC
